### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by feketerigo725** [OfficeDev/Timesheet#1]
Building "GoLocal.TimeTracker.MiddleTier" will fail...
Is not the code incomplete?

> error CS0246: The type or namespace name 'GraphAppUserService' could not be found.  (are you missing a using directive or an assembly reference?)
> error CS0246: The type or namespace name 'GraphAppTasksService' could not be found.  (are you missing a using directive or an assembly reference?)
> error CS0246: The type or namespace name 'GraphAppMailService' could not be found.  (are you missing a using directive or an assembly reference?)
> error CS0246: The type or namespace name 'GraphAppCalendarService' could not be found.  (are you missing a using directive or an assembly reference?)
> 
> error CS0234: The type or namespace name 'AppContext' does not exist in the namespace 'GoLocal.TimeTracker.MiddleTier.Services' (are you missing an assembly reference?)

**Comment by abhishek-pc** [comment]
AppContext folder with the service references was excluded in commit as it was specified to be ignored in git settings, .gitignore has been updated so that the references get added
